# Classifying Penguins with Keras

In [11]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [14]:
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [17]:
# Drop Nan rows
penguins = penguins.dropna()

In [39]:
# Shuffle the data
penguins = penguins.sample(frac=1, random_state=42).reset_index(drop=True)

In [40]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,2900.0,38.6,17.0,188.0,True,False
1,2900.0,34.5,18.1,187.0,True,False
2,3950.0,51.9,19.5,206.0,False,True
3,4500.0,42.5,20.7,197.0,False,True
4,4400.0,41.3,21.1,195.0,False,True
...,...,...,...,...,...,...
328,3550.0,50.9,19.1,196.0,False,True
329,3950.0,40.5,18.9,180.0,False,True
330,5450.0,52.5,15.6,221.0,False,True
331,4500.0,53.5,19.9,205.0,False,True
332,4550.0,52.8,20.0,205.0,False,True

In [41]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.055556,0.236364,0.464286,0.271186,1.0,0.0
1,0.055556,0.087273,0.595238,0.254237,1.0,0.0
2,0.347222,0.720000,0.761905,0.576271,0.0,1.0
3,0.500000,0.378182,0.904762,0.423729,0.0,1.0
4,0.472222,0.334545,0.952381,0.389831,0.0,1.0
...,...,...,...,...,...,...
328,0.236111,0.683636,0.714286,0.406780,0.0,1.0
329,0.347222,0.305455,0.690476,0.135593,0.0,1.0
330,0.763889,0.741818,0.297619,0.830508,0.0,1.0
331,0.500000,0.778182,0.809524,0.559322,0.0,1.0
332,0.513889,0.752727,0.821429,0.559322,0.0,1.0

In [42]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1         Adelie
2      Chinstrap
3         Adelie
4         Adelie
         ...
328    Chinstrap
329       Adelie
330       Gentoo
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: str

array([0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0,
       2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 2, 1, 0,
       2, 2, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 0, 1, 1, 2, 2, 0, 2,
       1, 1, 0, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 1, 0, 0, 0, 2, 2, 0, 1, 2,
       2, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       0, 2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 1, 2, 1, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 2, 0,
       0, 0, 2, 0, 1, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0,
       0, 2, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0, 1,
       2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1,
       0, 0, 2, 0, 1, 0, 2, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 0, 2,
       2, 0, 0, 1, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0,
       2, 1, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0,
       2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0,
       2, 1, 1], dtype=int8)

In [43]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [44]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [46]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

c:\Users\ldcal\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.3645 - loss: 1.0980 - val_accuracy: 0.7059 - val_loss: 1.0910
Epoch 2/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5156 - loss: 1.0936

c:\Users\ldcal\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5619 - loss: 1.0916 - val_accuracy: 0.7353 - val_loss: 1.0862
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6020 - loss: 1.0879 - val_accuracy: 0.7059 - val_loss: 1.0818
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6087 - loss: 1.0839 - val_accuracy: 0.7059 - val_loss: 1.0771
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6054 - loss: 1.0795 - val_accuracy: 0.7647 - val_loss: 1.0709
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6856 - loss: 1.0732 - val_accuracy: 0.6471 - val_loss: 1.0652
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6622 - loss: 1.0664 - val_accuracy: 0.5882 - val_loss: 1.0591
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6154 - loss: 1.0598 - val_accuracy: 0.5882 - val_loss: 1.0531
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6154 - loss: 1.0530 - val_accuracy: 0.5588 - val_loss: 1.0473
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6488 - loss: 1.0464 - val_accuracy: 0.5294 - val_loss: 1.0417
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5786 - loss: 1.0400 - val_accuracy: 0.5000 - val_loss: 1.0361
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5987 - loss: 1.0336 - val_accuracy: 0.5000 - val_loss: 1.0306
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5485 - loss: 1.0266 - val_accuracy: 0.5000 - val_loss: 1.0245
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5351 - loss: 1.0184 - val_accuracy: 0.5294 - val_loss: 1.0185
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5518 - loss: 1.0110 - val_accuracy: 0.5294 - val_loss: 1.0127
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5753 - loss: 1.0037 - val_accuracy: 0.5294 - val_loss: 1.0071
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5753 - loss: 0.9967 - val_accuracy: 0.5882 - val_loss: 1.0012
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5987 - loss: 0.9896 - val_accuracy: 0.5588 - val_loss: 0.9959
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6054 - loss: 0.9825 - val_accuracy: 0.5882 - val_loss: 0.9902
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6288 - loss: 0.9748 - val_accuracy: 0.5882 - val_loss: 0.9843
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6087 - loss: 0.9674 - val_accuracy: 0.6471 - val_loss: 0.9772
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6589 - loss: 0.9599 - val_accuracy: 0.6176 - val_loss: 0.9716
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6522 - loss: 0.9518 - val_accuracy: 0.6765 - val_loss: 0.9647
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6555 - loss: 0.9438 - val_accuracy: 0.7059 - val_loss: 0.9573
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6722 - loss: 0.9347 - val_accuracy: 0.7353 - val_loss: 0.9494
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6789 - loss: 0.9263 - val_accuracy: 0.7647 - val_loss: 0.9406
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7224 - loss: 0.9174 - val_accuracy: 0.7647 - val_loss: 0.9340
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7023 - loss: 0.9086 - val_accuracy: 0.7941 - val_loss: 0.9254
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7291 - loss: 0.8993 - val_accuracy: 0.7941 - val_loss: 0.9182
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7358 - loss: 0.8905 - val_accuracy: 0.7941 - val_loss: 0.9089
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7492 - loss: 0.8810 - val_accuracy: 0.7941 - val_loss: 0.9003
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7659 - loss: 0.8717 - val_accuracy: 0.8235 - val_loss: 0.8927
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7625 - loss: 0.8623 - val_accuracy: 0.8235 - val_loss: 0.8832
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7659 - loss: 0.8523 - val_accuracy: 0.8235 - val_loss: 0.8755
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7692 - loss: 0.8429 - val_accuracy: 0.8235 - val_loss: 0.8670
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7726 - loss: 0.8333 - val_accuracy: 0.8235 - val_loss: 0.8580
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7659 - loss: 0.8235 - val_accuracy: 0.8235 - val_loss: 0.8476
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7726 - loss: 0.8131 - val_accuracy: 0.8235 - val_loss: 0.8391
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7759 - loss: 0.8026 - val_accuracy: 0.8235 - val_loss: 0.8288
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7793 - loss: 0.7918 - val_accuracy: 0.8235 - val_loss: 0.8209
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7759 - loss: 0.7813 - val_accuracy: 0.8235 - val_loss: 0.8103
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7793 - loss: 0.7695 - val_accuracy: 0.8235 - val_loss: 0.7977
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7793 - loss: 0.7580 - val_accuracy: 0.8235 - val_loss: 0.7862
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7826 - loss: 0.7455 - val_accuracy: 0.8235 - val_loss: 0.7739
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7826 - loss: 0.7333 - val_accuracy: 0.8235 - val_loss: 0.7614
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7826 - loss: 0.7207 - val_accuracy: 0.8235 - val_loss: 0.7499
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7860 - loss: 0.7079 - val_accuracy: 0.8235 - val_loss: 0.7372
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7860 - loss: 0.6956 - val_accuracy: 0.8235 - val_loss: 0.7260
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7860 - loss: 0.6836 - val_accuracy: 0.8235 - val_loss: 0.7135
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7860 - loss: 0.6715 - val_accuracy: 0.8235 - val_loss: 0.6990
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.6598 - val_accuracy: 0.8235 - val_loss: 0.6909
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7893 - loss: 0.6482 - val_accuracy: 0.8235 - val_loss: 0.6755
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7893 - loss: 0.6381 - val_accuracy: 0.8235 - val_loss: 0.6626
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.6273 - val_accuracy: 0.8235 - val_loss: 0.6542
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7893 - loss: 0.6167 - val_accuracy: 0.8235 - val_loss: 0.6445
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7893 - loss: 0.6065 - val_accuracy: 0.8235 - val_loss: 0.6326
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7893 - loss: 0.5963 - val_accuracy: 0.8235 - val_loss: 0.6240
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7893 - loss: 0.5863 - val_accuracy: 0.8235 - val_loss: 0.6142
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7893 - loss: 0.5764 - val_accuracy: 0.8235 - val_loss: 0.5994
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7893 - loss: 0.5678 - val_accuracy: 0.8235 - val_loss: 0.5920
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.5583 - val_accuracy: 0.8235 - val_loss: 0.5809
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.5497 - val_accuracy: 0.8235 - val_loss: 0.5736
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7893 - loss: 0.5411 - val_accuracy: 0.8235 - val_loss: 0.5642
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7893 - loss: 0.5327 - val_accuracy: 0.8235 - val_loss: 0.5559
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.5247 - val_accuracy: 0.8235 - val_loss: 0.5462
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7926 - loss: 0.5164 - val_accuracy: 0.8235 - val_loss: 0.5380
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7926 - loss: 0.5087 - val_accuracy: 0.8235 - val_loss: 0.5264
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.5014 - val_accuracy: 0.8235 - val_loss: 0.5183
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4947 - val_accuracy: 0.8235 - val_loss: 0.5143
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.4878 - val_accuracy: 0.8235 - val_loss: 0.5039
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7926 - loss: 0.4816 - val_accuracy: 0.8235 - val_loss: 0.4968
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4753 - val_accuracy: 0.8235 - val_loss: 0.4919
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7926 - loss: 0.4696 - val_accuracy: 0.8235 - val_loss: 0.4858
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7926 - loss: 0.4642 - val_accuracy: 0.8235 - val_loss: 0.4789
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4588 - val_accuracy: 0.8235 - val_loss: 0.4763
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4536 - val_accuracy: 0.8235 - val_loss: 0.4686
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7926 - loss: 0.4489 - val_accuracy: 0.8235 - val_loss: 0.4620
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.4443 - val_accuracy: 0.8235 - val_loss: 0.4561
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7926 - loss: 0.4393 - val_accuracy: 0.8235 - val_loss: 0.4510
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7926 - loss: 0.4352 - val_accuracy: 0.8235 - val_loss: 0.4449
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4304 - val_accuracy: 0.8235 - val_loss: 0.4427
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4263 - val_accuracy: 0.8235 - val_loss: 0.4346
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.4223 - val_accuracy: 0.8235 - val_loss: 0.4308
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7926 - loss: 0.4176 - val_accuracy: 0.8235 - val_loss: 0.4265
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.4142 - val_accuracy: 0.8235 - val_loss: 0.4240
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.4109 - val_accuracy: 0.8235 - val_loss: 0.4187
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7926 - loss: 0.4065 - val_accuracy: 0.8235 - val_loss: 0.4154
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7926 - loss: 0.4031 - val_accuracy: 0.8235 - val_loss: 0.4110
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7926 - loss: 0.3994 - val_accuracy: 0.8235 - val_loss: 0.4073
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.3963 - val_accuracy: 0.8235 - val_loss: 0.4023
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7926 - loss: 0.3924 - val_accuracy: 0.8235 - val_loss: 0.4016
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.3891 - val_accuracy: 0.8235 - val_loss: 0.3954
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.3859 - val_accuracy: 0.8235 - val_loss: 0.3918
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7960 - loss: 0.3821 - val_accuracy: 0.8235 - val_loss: 0.3882
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7960 - loss: 0.3803 - val_accuracy: 0.8235 - val_loss: 0.3842
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7960 - loss: 0.3759 - val_accuracy: 0.8235 - val_loss: 0.3815
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7993 - loss: 0.3732 - val_accuracy: 0.8529 - val_loss: 0.3782
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7993 - loss: 0.3697 - val_accuracy: 0.8529 - val_loss: 0.3753
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8060 - loss: 0.3667 - val_accuracy: 0.8529 - val_loss: 0.3721
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8027 - loss: 0.3634 - val_accuracy: 0.8529 - val_loss: 0.3681
11/11 - 0s - 6ms/step - accuracy: 0.8108 - loss: 0.3618

In [55]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 5, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.9967 - loss: 0.0127 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 2/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9967 - loss: 0.0119 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 3/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9933 - loss: 0.0114 - val_accuracy: 1.0000 - val_loss: 0.0023
Epoch 4/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9967 - loss: 0.0118 - val_accuracy: 1.0000 - val_loss: 0.0024
Epoch 5/5
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9967 - loss: 0.0112 - val_accuracy: 1.0000 - val_loss: 0.0031
11/11 - 0s - 7ms/step - accuracy: 0.9970 - loss: 0.0101

In [50]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_false = model_logit_false.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9866 - loss: 0.1061 - val_accuracy: 1.0000 - val_loss: 0.0803
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9866 - loss: 0.1038 - val_accuracy: 1.0000 - val_loss: 0.0794
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9833 - loss: 0.1003 - val_accuracy: 1.0000 - val_loss: 0.0807
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0986 - val_accuracy: 1.0000 - val_loss: 0.0771
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0971 - val_accuracy: 1.0000 - val_loss: 0.0756
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0956 - val_accuracy: 1.0000 - val_loss: 0.0727
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9833 - loss: 0.0946 - val_accuracy: 1.0000 - val_loss: 0.0746
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9833 - loss: 0.0927 - val_accuracy: 1.0000 - val_loss: 0.0677
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9866 - loss: 0.0913 - val_accuracy: 1.0000 - val_loss: 0.0696
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.0906 - val_accuracy: 1.0000 - val_loss: 0.0689
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0888 - val_accuracy: 1.0000 - val_loss: 0.0698
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9833 - loss: 0.0874 - val_accuracy: 1.0000 - val_loss: 0.0660
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0859 - val_accuracy: 1.0000 - val_loss: 0.0636
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0848 - val_accuracy: 1.0000 - val_loss: 0.0631
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9866 - loss: 0.0837 - val_accuracy: 1.0000 - val_loss: 0.0590
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0823 - val_accuracy: 1.0000 - val_loss: 0.0585
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9833 - loss: 0.0812 - val_accuracy: 1.0000 - val_loss: 0.0569
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9866 - loss: 0.0797 - val_accuracy: 1.0000 - val_loss: 0.0575
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9866 - loss: 0.0790 - val_accuracy: 1.0000 - val_loss: 0.0605
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9833 - loss: 0.0780 - val_accuracy: 1.0000 - val_loss: 0.0582
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.0765 - val_accuracy: 1.0000 - val_loss: 0.0539
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0755 - val_accuracy: 1.0000 - val_loss: 0.0546
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0749 - val_accuracy: 1.0000 - val_loss: 0.0551
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0737 - val_accuracy: 1.0000 - val_loss: 0.0506
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9900 - loss: 0.0724 - val_accuracy: 1.0000 - val_loss: 0.0501
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9900 - loss: 0.0711 - val_accuracy: 1.0000 - val_loss: 0.0494
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9866 - loss: 0.0710 - val_accuracy: 1.0000 - val_loss: 0.0494
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.0702 - val_accuracy: 1.0000 - val_loss: 0.0482
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0683 - val_accuracy: 1.0000 - val_loss: 0.0475
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0681 - val_accuracy: 1.0000 - val_loss: 0.0465
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0667 - val_accuracy: 1.0000 - val_loss: 0.0455
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9900 - loss: 0.0655 - val_accuracy: 1.0000 - val_loss: 0.0425
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.0647 - val_accuracy: 1.0000 - val_loss: 0.0403
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9866 - loss: 0.0637 - val_accuracy: 1.0000 - val_loss: 0.0428
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9900 - loss: 0.0626 - val_accuracy: 1.0000 - val_loss: 0.0428
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9900 - loss: 0.0620 - val_accuracy: 1.0000 - val_loss: 0.0397
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0609 - val_accuracy: 1.0000 - val_loss: 0.0413
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9866 - loss: 0.0605 - val_accuracy: 1.0000 - val_loss: 0.0362
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9900 - loss: 0.0603 - val_accuracy: 1.0000 - val_loss: 0.0364
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9900 - loss: 0.0583 - val_accuracy: 1.0000 - val_loss: 0.0377
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0578 - val_accuracy: 1.0000 - val_loss: 0.0379
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9900 - loss: 0.0566 - val_accuracy: 1.0000 - val_loss: 0.0357
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0566 - val_accuracy: 1.0000 - val_loss: 0.0352
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0555 - val_accuracy: 1.0000 - val_loss: 0.0319
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9900 - loss: 0.0553 - val_accuracy: 1.0000 - val_loss: 0.0317
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9900 - loss: 0.0543 - val_accuracy: 1.0000 - val_loss: 0.0324
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9900 - loss: 0.0534 - val_accuracy: 1.0000 - val_loss: 0.0320
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0524 - val_accuracy: 1.0000 - val_loss: 0.0314
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9866 - loss: 0.0520 - val_accuracy: 1.0000 - val_loss: 0.0289
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9933 - loss: 0.0512 - val_accuracy: 1.0000 - val_loss: 0.0309
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0511 - val_accuracy: 1.0000 - val_loss: 0.0295
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0497 - val_accuracy: 1.0000 - val_loss: 0.0289
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9933 - loss: 0.0492 - val_accuracy: 1.0000 - val_loss: 0.0326
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9866 - loss: 0.0483 - val_accuracy: 1.0000 - val_loss: 0.0271
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0479 - val_accuracy: 1.0000 - val_loss: 0.0296
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9866 - loss: 0.0475 - val_accuracy: 1.0000 - val_loss: 0.0268
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9933 - loss: 0.0468 - val_accuracy: 1.0000 - val_loss: 0.0266
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0458 - val_accuracy: 1.0000 - val_loss: 0.0268
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0453 - val_accuracy: 1.0000 - val_loss: 0.0273
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0452 - val_accuracy: 1.0000 - val_loss: 0.0245
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9900 - loss: 0.0446 - val_accuracy: 1.0000 - val_loss: 0.0228
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9933 - loss: 0.0435 - val_accuracy: 1.0000 - val_loss: 0.0246
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0431 - val_accuracy: 1.0000 - val_loss: 0.0232
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0432 - val_accuracy: 1.0000 - val_loss: 0.0218
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9900 - loss: 0.0425 - val_accuracy: 1.0000 - val_loss: 0.0209
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0420 - val_accuracy: 1.0000 - val_loss: 0.0213
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9933 - loss: 0.0418 - val_accuracy: 1.0000 - val_loss: 0.0233
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9900 - loss: 0.0404 - val_accuracy: 1.0000 - val_loss: 0.0207
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9933 - loss: 0.0405 - val_accuracy: 1.0000 - val_loss: 0.0203
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9933 - loss: 0.0397 - val_accuracy: 1.0000 - val_loss: 0.0206
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9933 - loss: 0.0397 - val_accuracy: 1.0000 - val_loss: 0.0224
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9900 - loss: 0.0391 - val_accuracy: 1.0000 - val_loss: 0.0204
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0390 - val_accuracy: 1.0000 - val_loss: 0.0185
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9933 - loss: 0.0389 - val_accuracy: 1.0000 - val_loss: 0.0214
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0375 - val_accuracy: 1.0000 - val_loss: 0.0196
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0371 - val_accuracy: 1.0000 - val_loss: 0.0201
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9933 - loss: 0.0371 - val_accuracy: 1.0000 - val_loss: 0.0204
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9900 - loss: 0.0372 - val_accuracy: 1.0000 - val_loss: 0.0196
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0362 - val_accuracy: 1.0000 - val_loss: 0.0177
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9933 - loss: 0.0361 - val_accuracy: 1.0000 - val_loss: 0.0190
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9900 - loss: 0.0362 - val_accuracy: 1.0000 - val_loss: 0.0177
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9900 - loss: 0.0355 - val_accuracy: 1.0000 - val_loss: 0.0164
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9933 - loss: 0.0349 - val_accuracy: 1.0000 - val_loss: 0.0183
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9900 - loss: 0.0347 - val_accuracy: 1.0000 - val_loss: 0.0177
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9933 - loss: 0.0345 - val_accuracy: 1.0000 - val_loss: 0.0158
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9933 - loss: 0.0336 - val_accuracy: 1.0000 - val_loss: 0.0180
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9933 - loss: 0.0338 - val_accuracy: 1.0000 - val_loss: 0.0193
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0340 - val_accuracy: 1.0000 - val_loss: 0.0192
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0335 - val_accuracy: 1.0000 - val_loss: 0.0160
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9933 - loss: 0.0325 - val_accuracy: 1.0000 - val_loss: 0.0151
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0328 - val_accuracy: 1.0000 - val_loss: 0.0174
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0324 - val_accuracy: 1.0000 - val_loss: 0.0160
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9900 - loss: 0.0318 - val_accuracy: 1.0000 - val_loss: 0.0148
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9933 - loss: 0.0317 - val_accuracy: 1.0000 - val_loss: 0.0151
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9900 - loss: 0.0313 - val_accuracy: 1.0000 - val_loss: 0.0144
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9933 - loss: 0.0308 - val_accuracy: 1.0000 - val_loss: 0.0129
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9900 - loss: 0.0304 - val_accuracy: 1.0000 - val_loss: 0.0162
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9967 - loss: 0.0308 - val_accuracy: 1.0000 - val_loss: 0.0150
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9900 - loss: 0.0297 - val_accuracy: 1.0000 - val_loss: 0.0137
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9933 - loss: 0.0297 - val_accuracy: 1.0000 - val_loss: 0.0130
11/11 - 0s - 5ms/step - accuracy: 0.9940 - loss: 0.0274

In [11]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=float32)

In [49]:
penguins['species']

0         Adelie
1         Adelie
2      Chinstrap
3         Adelie
4         Adelie
         ...
328    Chinstrap
329       Adelie
330       Gentoo
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: str

In [48]:
penguins_y

array([0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0,
       2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 2, 1, 0,
       2, 2, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 0, 1, 1, 2, 2, 0, 2,
       1, 1, 0, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 1, 0, 0, 0, 2, 2, 0, 1, 2,
       2, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       0, 2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 0, 0, 2,
       2, 0, 2, 2, 0, 2, 1, 2, 1, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 2, 0,
       0, 0, 2, 0, 1, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 0, 2, 0,
       0, 2, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 2, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0, 1,
       2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1,
       0, 0, 2, 0, 1, 0, 2, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 0, 2,
       2, 0, 0, 1, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0,
       2, 1, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0,
       2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0,
       2, 1, 1], dtype=int8)