# In Class Activity April 14th, 2026

### Importing libraries, preparing data, initial EDA

In [2]:
# importing libraries (feel free to add more if you want to explore other things)
import numpy as np
import pandas as pd
import sweetviz as sv
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, accuracy_score, classification_report
import optuna

In [3]:
# importing data
adult = pd.read_csv('adult.csv')
adult.head(20)

    age         workclass  fnlwgt     education  ...  capital-loss hours-per-week native-country income
0    25           Private  226802          11th  ...             0             40  United-States  <=50K
1    38           Private   89814       HS-grad  ...             0             50  United-States  <=50K
2    28         Local-gov  336951    Assoc-acdm  ...             0             40  United-States   >50K
3    44           Private  160323  Some-college  ...             0             40  United-States   >50K
4    18                 ?  103497  Some-college  ...             0             30  United-States  <=50K
5    34           Private  198693          10th  ...             0             30  United-States  <=50K
6    29                 ?  227026       HS-grad  ...             0             40  United-States  <=50K
7    63  Self-emp-not-inc  104626   Prof-school  ...             0             32  United-States   >50K
8    24           Private  369667  Some-college  ...             0             40  United-States  <=50K
9    55           Private  104996       7th-8th  ...             0             10  United-States  <=50K
10   65           Private  184454       HS-grad  ...             0             40  United-States   >50K
11   36       Federal-gov  212465     Bachelors  ...             0             40  United-States  <=50K
12   26           Private   82091       HS-grad  ...             0             39  United-States  <=50K
13   58                 ?  299831       HS-grad  ...             0             35  United-States  <=50K
14   48           Private  279724       HS-grad  ...             0             48  United-States   >50K
15   43           Private  346189       Masters  ...             0             50  United-States   >50K
16   20         State-gov  444554  Some-college  ...             0             25  United-States  <=50K
17   43           Private  128354       HS-grad  ...             0             30  United-States  <=50K
18   37           Private   60548       HS-grad  ...             0             20  United-States  <=50K
19   40           Private   85019     Doctorate  ...             0             45              ?   >50K

[20 rows x 15 columns]

In [4]:
# initial EDA with sweetviz
report = sv.analyze(adult)
report.show_html('sweet_report.html')

# you are welcome to replace this cell with your own EDA, but make sure to include
# some visualizations and insights about the data

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:01 -> (00:00 left)

Report sweet_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### In the markdown cell below describe what you learned from your EDA and how it will inform your modeling decisions

### Data Preprocessing (minimal) and Baseline Model

In [5]:
# data cleaning and preprocessing

# changing ? to NaN
adult = adult.replace('?', np.nan)

#education and education num are redundant, so we can drop one of them
adult = adult.drop('education', axis=1)

# target variable is income with 2 levels, so we can encode it as 0 and 1
adult['income'] = adult['income'].apply(lambda x: 1 if x == '>50K' else 0)

# change dtype categorical variables to category
categorical_cols = adult.select_dtypes(include='object').columns
adult[categorical_cols] = adult[categorical_cols].astype('category')


adult.head(20)

<positron-console-cell-5>:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.

    age         workclass  fnlwgt  educational-num      marital-status  ... capital-gain capital-loss hours-per-week native-country  income
0    25           Private  226802                7       Never-married  ...            0            0             40  United-States       0
1    38           Private   89814                9  Married-civ-spouse  ...            0            0             50  United-States       0
2    28         Local-gov  336951               12  Married-civ-spouse  ...            0            0             40  United-States       1
3    44           Private  160323               10  Married-civ-spouse  ...         7688            0             40  United-States       1
4    18               NaN  103497               10       Never-married  ...            0            0             30  United-States       0
5    34           Private  198693                6       Never-married  ...            0            0             30  United-States       0
6    29               NaN  227026                9       Never-married  ...            0            0             40  United-States       0
7    63  Self-emp-not-inc  104626               15  Married-civ-spouse  ...         3103            0             32  United-States       1
8    24           Private  369667               10       Never-married  ...            0            0             40  United-States       0
9    55           Private  104996                4  Married-civ-spouse  ...            0            0             10  United-States       0
10   65           Private  184454                9  Married-civ-spouse  ...         6418            0             40  United-States       1
11   36       Federal-gov  212465               13  Married-civ-spouse  ...            0            0             40  United-States       0
12   26           Private   82091                9       Never-married  ...            0            0             39  United-States       0
13   58               NaN  299831                9  Married-civ-spouse  ...            0            0             35  United-States       0
14   48           Private  279724                9  Married-civ-spouse  ...         3103            0             48  United-States       1
15   43           Private  346189               14  Married-civ-spouse  ...            0            0             50  United-States       1
16   20         State-gov  444554               10       Never-married  ...            0            0             25  United-States       0
17   43           Private  128354                9  Married-civ-spouse  ...            0            0             30  United-States       0
18   37           Private   60548                9             Widowed  ...            0            0             20  United-States       0
19   40           Private   85019               16  Married-civ-spouse  ...            0            0             45            NaN       1

[20 rows x 14 columns]

In [6]:
# defining features and target variable
X = adult.drop('income', axis=1)
y = adult['income']

# splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, 
                                                    random_state=42, stratify=y)

In [7]:
# building xgboost default model and evaluating with stratified k-fold cross validation
xgb_cv = XGBClassifier(enable_categorical=True, random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# each fold done gets an equal value of 0 and 1 
cv_scores = cross_val_score(xgb_cv, X, y, cv=skf, scoring='f1')
print(f'Cross-validated F1 scores: {cv_scores}')
print(f'Mean F1 score: {cv_scores.mean()}')

Cross-validated F1 scores: [0.70680507 0.70892566 0.70898981 0.72424942 0.71086556]
Mean F1 score: 0.7119671046056588

### Use the markdown cell below to describe your baseline model performance and how you will try to improve it

### Model feature exploration

In the code cell below, explore different features of XGBoost and how they work (e.g. scale_pos_weight, max_depth, learning_rate).
Use stratified k-fold cross or repeated stratified k-fold cross validation with your model building. 
You should explore at least 3 different features of XGBoost.
Identify the model that performs best.

In [ ]:
# explorimg different features of xgboost and tuning hyperparameters usingh stratified k-fold cross validation.
# explore 3 differnet features.

Cross-validated F1 scores for default XGB: [0.70680507 0.70892566 0.70898981 0.72424942 0.71086556]
Mean F1 score for default XGB: 0.7119671046056588

### Tuning with GridSearchCV

Use the code cell below to set up your parameter grid and run GridSearchCV with your preferred model from above. You should tune 4-5 hyperparameters utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [ ]:
# your code here

### Tuning with RandomizedSearchCV

Using the code cell below as a starting point, tune your preferred model from above. Tune the same 4-5 hyperparameters from above utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [ ]:
# tuning xgboost classifier with RandomizedSearchCV (tune more parameters than shown here)
param_dist = {
    'scale_pos_weight': np.linspace(1.0, 10.0, num=10),
    'max_depth': np.arange(3, 11),
    'learning_rate': np.linspace(0.01, 0.3, num=10)
}

# replace this placeholder model with your preferred model from above

xgb_random = RandomizedSearchCV(XGBClassifier(random_state=42, enable_categorical=True),
                                param_distributions=param_dist, n_iter=20, cv=skf, scoring='f1', random_state=42)
xgb_random.fit(X_train, y_train)
print(f'Best parameters from RandomizedSearchCV: {xgb_random.best_params_}')
print(f'Best F1 score from RandomizedSearchCV: {xgb_random.best_score_}')   

# build your preferred model from above using best parameters from your RandomizedSearchCV
# and evaluate on the test set

xgb_random_best = XGBClassifier(random_state=42, scale_pos_weight=xgb_random.best_params_['scale_pos_weight'], 
                                max_depth=xgb_random.best_params_['max_depth'], 
                                learning_rate=xgb_random.best_params_['learning_rate'], 
                                enable_categorical=True)
xgb_random_best.fit(X_train, y_train)
y_pred_random = xgb_random_best.predict(X_test)
print(f'Classification report for RandomizedSearchCV-tuned model:\n{classification_report(y_test, y_pred_random)}')

### Tuning with Optuna

Using the code cell below as a starting point, tune your preferred model from above. You should tune the same 4-5 parameters as above using cross validation. Train a final model using the best hyperparameters and report your model performance.

In [ ]:
# tuning with Optuna (tune more parameters than shown here)
def objective(trial):
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1.0, 10.0)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
    
    # replace this placeholder model with your preferred model from above
    
    xgb_optuna = XGBClassifier(random_state=42, scale_pos_weight=scale_pos_weight, 
                               max_depth=max_depth,  learning_rate=learning_rate, enable_categorical=True)
    
    cv_scores = cross_val_score(xgb_optuna, X, y, cv=skf, scoring='f1')
    return cv_scores.mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20, show_progress_bar=True)

print(f'Best parameters from Optuna: {study.best_params}')
print(f'Best F1 score from Optuna: {study.best_value}')

# build preferred model from above with best parameters from Optuna and evaluate on the test set
xgb_optuna_best = XGBClassifier(random_state=42, scale_pos_weight=study.best_params['scale_pos_weight'], 
                                  max_depth=study.best_params['max_depth'], 
                                  learning_rate=study.best_params['learning_rate'], 
                                  enable_categorical=True)
xgb_optuna_best.fit(X_train, y_train)
y_pred_optuna = xgb_optuna_best.predict(X_test)
print(f'Classification report for Optuna-tuned model:\n{classification_report(y_test, y_pred_optuna)}')

### Tuning results

In the markdown cell below describe your experience tuning with the different methods. Which produced the best results? Which do you prefer?